services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/code/backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on:
        - backend
    volumes:
      - ./frontend:/code
      - /code/node_modules
