services:
  db:
    image: "postgres:13"  # Update version as needed; postgres:17 may not be valid
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bmbenkyou"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpasswordtemporary
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on:
        - backend

volumes:
  postgres_data:
