services:
  db:
    image: "postgres:13"
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpasswordtemporary
      POSTGRES_DB: db_test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpasswordtemporary
      POSTGRES_DB: db_test
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/code/backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on:
        - backend
    volumes:
      - ./frontend:/code
      - /code/node_modules
volumes:
  postgres_data:
