# Generated by Django 5.1.6 on 2025-04-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_studyplan_studyplanitem'),
        ('chat', 'create_file_models'),
    ]

    operations = [
    ]
