# Generated by Django 5.1.6 on 2025-04-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.uploadedfile'),
        ),
    ]
