# Generated by Django 5.1.6 on 2025-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_flashcardset_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
