# Generated by Django 5.1.6 on 2025-03-02 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/flashcards/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/flashcards/')),
                ('questions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/quiz/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/quiz/')),
                ('questions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
