# Generated by Django 4.2.16 on 2024-12-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studyplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
