# Generated by Django 4.2.16 on 2024-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_quiz_file_alter_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='generated_content',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
