# Generated by Django 4.2.16 on 2024-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('flashcard', 'Flashcard')], max_length=20, null=True),
        ),
    ]
