# Generated by Django 4.2.16 on 2024-12-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_session_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.quiz'),
        ),
    ]
